GET {{url}}/todos/?page={{page}}&limit={{limit}}&search={{search}}&sort_by={{sort_by}}&order={{order}}
Accept: application/json
Authorization: Token {{token}}

###
DELETE {{url}}/todos/{{todo.id}}
Accept: application/json
Authorization: Token {{token}}

###
PUT {{url}}/todos/{{todo.id}}
Content-Type: application/json
Authorization: Token {{token}}

{
  "title": "{{todo.title}}",
  "description": "{{todo.description}}"
}

###
POST {{url}}/todos/
Content-Type: application/json
Authorization: Token {{token}}

{
  "title": "{{todo.title}}",
  "description": "{{todo.description}}"
}

###
